### ISSUE TITLE
If you are not logged in to your github account, your homepage will not display 1990

### ISSUE THREAD

**Issue by GAOli-cong** [antfu/1990-script#6]
If you are not logged in to your github account, your homepage will not display 1990

**Comment by antfu** [comment]
Please provide more info.

**Comment by mt190502** [comment]
> Please provide more info.

![image](https://user-images.githubusercontent.com/62564400/170422150-4c49d126-8279-4e9a-b080-3db086c28a9d.png)

![image](https://user-images.githubusercontent.com/62564400/170422499-eedc417d-61cc-4a9b-b0de-294cc8c1e9ad.png)
